apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mkc

resources:
  - namespace/namespace.yaml
  - secrets/service-secret.example.yaml
  - config/gateway-config.yaml
  - config/ai-service-config.yaml
  - mysql/statefulset.yaml
  - redis/statefulset.yaml
  - minio/deployment.yaml
  - milvus/etcd-statefulset.yaml
  - milvus/milvus-statefulset.yaml
  - gateway/deployment.yaml
  - ai-service/deployment.yaml
  - ai-worker/deployment.yaml
  - client/deployment.yaml
  - ingress/ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: mkc
