apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: gateway
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 768Mi
              cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: ai-service
          imagePullPolicy: Always
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 3Gi
              cpu: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-worker
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ai-worker
          imagePullPolicy: Always
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 4Gi
              cpu: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: client
          imagePullPolicy: Always
